### ISSUE TITLE
Missing step while building the project (minor thing)

### ISSUE THREAD

**Issue by JanVelas** [VirtuosoChris/YarnMachine#1]
Hello :-)

Not really an issue, but I had to do one tiny extra step and thought I'd write it here, in case anyone else runs into the problem in the future.

In order to successfully generate the project, I had to first manually fetch the protobuf submodule:
```
git submodule update --init --recursive
```
- I found this in the [git book](https://git-scm.com/book/en/v2/Git-Tools-Submodules#:~:text=Cloning%20a%20Project%20with%20Submodules)

Otherwise the folder "./depends/protobuf" is empty and CMake fails with:
> CMake Error at CMakeLists.txt:30 (add_subdirectory):
> The source directory
>     ....../YarnMachine/depends/protobuf
> does not contain a CMakeLists.txt file.

Everything else generated and built just fine. 👍 

I would be happy if it was made into the instructions somehow, **if this is something that happens for everyone**.
This is a first time I'm making an issue, and maybe I could just make a pull request, tell me what you think.

---
PS: Just want to say I'm very glad this exists. 
I'm making my own tiny game engine for learning purposes and really want to use YarnSpinner in it.
I understand YS was made for unity, but I definitely think it would benefit the community to have a engine agnostic version.
If nothing else your project showed me that it can be done.

Thank you!
Jan

**Comment by VirtuosoChris** [comment]
Thanks, I'll make a note in the readme!
