### ISSUE TITLE
Error: Command <command name> unknown

### ISSUE THREAD

**Issue by JanVelas** [VirtuosoChris/YarnMachine#2]
Hello :-)

So far everything works just fine, but I ran into a single problem, which I'm not yet sure the cause of.
It's related to commands and manifests into the YarnTest (demo.cpp) console app like this:
```
[error]: Command fade_up unknown
[error]: Command 1.0 unknown
```
which happens when the script gets to this line
```
<<fade_up 1.0>>
```
As I'm just learning about YS it's by no means affecting me in any way, but I still thought I'd post it here.
## How to reproduce

I compiled the test dialog at https://try.yarnspinner.dev/ using both the ysc.exe in this repo (version 2.3.0), as well as the compiler built from the source (version 2.4.0), but the problem persists.

I'm attaching the compiler output + the source script here [YarnScript.zip](https://github.com/VirtuosoChris/YarnMachine/files/13785952/YarnScript.zip)

To reproduce the problem I copied the compiler output to the YarnTest.exe directory and ran it:
```
.....\build\Debug>YarnTest.exe
Type name of module to run :
YarnScript
Loading lines from : YarnScript-Lines.csv
Line database total lines : 37
Line database size (bytes) : 14104
Time spent in parsing (ms) : 2
Yarn Spinner is a language for writing conversations in games!
You can use it to write branching dialogue, and use that in a game engine!
For example, here's a choice between some options!
        1) Wow, some options!
        2) Can I put text inside options?
1
You got it, pal!
You can also write 'commands', which represent things that happen in the game!
In this editor, they'll appear as text:
> fade_up 1.0
[error]: Command fade_up unknown

[error]: Command 1.0 unknown

        1) Nice!
        2) But it didn't actually fade!
```

It's the only problem I ran into so far, and it doesn't affect me, but I will be poking around a bit more.

Thanks again,
Jan

**Comment by JanVelas** [comment]
I'm sorry, I think I realized that this is actually not an issue at all - it's my responsibility to define custom commands (like fade_up here).

I read up more of the [manual](https://docs.yarnspinner.dev/getting-started/writing-in-yarn/commands) and I'm a bit wiser than before.

I guess I got too excited and jumped the gun.

Hope I didn't waste your time!
Jan

**Comment by VirtuosoChris** [comment]
I made a note in the readme!  Maybe later some examples with audiovisual stuff with imgui / openal or something could be useful to add here.  Keep me posted on any other questions or issues!

**Comment by JanVelas** [comment]
Thank you, will do. :-)
I'm making use of imgui in my project as well, so trying to connect the two will likely be my next step.
If I get anything useful working I'll let you know, I'd like to give something back.
Although I expect to be working on this at snail's pace, with the holidays coming to an end and work resuming soon. 
So please don't feel any pressure from me, but I'm happy for your support, and look forward to this.
