### ISSUE TITLE
By default, include ProtoBuf header/source with the rest of the source code.

### ISSUE THREAD

**Issue by gamagan** [VirtuosoChris/YarnMachine#3]
Thanks for creating this. I just read over the YarnSpinner docs, and it seems like exactly the thing I was looking for, in order to create branching dialog for my toy game engine.

If I can make a suggestion: I think it would be a good idea to store the generated ProtoBuf files, along with the code. That way, people interested in this project can just download the code and build it, without having to download extra dependencies. Those ProtoBuf header/source files only need overwriting when the .proto file changes.

**Comment by JanVelas** [comment]
Hello! 
I'm a fellow "making a hobby game engine" person, and I'm writing this mostly to express my gratitude, that someone else takes interest in this project.
Unfortunately, I'm not quite sure what you mean by storing the ProtoBuf files along with the code. Is that not what's in the ./generated folder? The source .proto file is in the root of the repo and there's even some elaborate cmake target that seems to "automagically regenerate" the files. :-)
I'm very new to both ProtoBuf and this repo, so I'm sorry if I'm missing something - in that case please ignore my comment. :-)
Have a nice day!

**Comment by VirtuosoChris** [comment]
If @gamagan means the .yarnc files for the compiled test scripts, those appear to be in the repo as well alongside the .yarn files.

Also just a note while I'm here, per the discussion here, https://github.com/YarnSpinnerTool/YarnSpinner/issues/299#issuecomment-1905063615

There's now an official c++ implementation as part of the Unreal plugin.  I have not assessed it yet to see if it does everything my VM does / is fully standalone enough to deprecate mine, although it's likely to be more up to date.

https://github.com/YarnSpinnerTool/YarnSpinner-Unreal/tree/17ede9aeb3dfaf4845b9fa344e4642fd0461ab43/Source/YarnSpinner/Private/YarnSpinnerCore

Doing that assessment is on the triage list for my game.  If I decide NOT to use the official code I'll add documentation about the differences and reasons for that decision, as well as making sure this VM is up to date with recent yarn runtime changes.

**Comment by VirtuosoChris** [comment]
I'm gonna close the issue since there's no followup.

Re. my comment about looking at the latest changes, I looked at the changelog and there doesn't seem to be anything breaking that's relevant to this VM project, just new markup, etc.   Yarn 3 apparently will have a bunch of new stuff so I can reevaluate then, but my instinct is to keep this project going for my own engine rather than forking off of the Unreal plugin code.
